// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import TextareaAutogrow from "stimulus-textarea-autogrow";
application.register("textarea-autogrow", TextareaAutogrow);

import RevealController from "@stimulus-components/reveal";
application.register("reveal", RevealController);

import Clipboard from "@stimulus-components/clipboard";
application.register("clipboard", Clipboard);

import ScrollHeightController from "./scroll_height_controller";
application.register("scroll-height", ScrollHeightController);

import UrlOpenerController from "./url_opener_controller";
application.register("url-opener", UrlOpenerController);
